### ISSUE TITLE
Allow override of jar instead if assuming assembly target

### ISSUE THREAD

**Issue by fooblahblah** [saksdirect/sbt-aws-lambda#11]
I'm building a complex Lambda function which needs extra assets and use the universal packager to create a zip (containing the assembly jar under /lib in the zip). I'd like to be able to override the jar parameter of doUpdateLambda and doCreateLambda respectively. I think if the do\* functions were not private I could override using standard SBT functionality. Otherwise, using some setting I can define would work too.

**Comment by fooblahblah** [comment]
So I forked the repo and removed the private modifier for *doCreateLambda* and *doUpdateLambda* as a test.

Note the jar arg is now my custom jar. This works, but I can see the merit of keeping the method private and exposing a setting.

```
updateLambda := doUpdateLambda(
  region = region.value,
  jar = (packageBin in Universal).value,
  s3Bucket = s3Bucket.value,
  lambdaName = lambdaName.value,
  handlerName = handlerName.value,
  lambdaHandlers = lambdaHandlers.value
)
createLambda := doCreateLambda(
  region = region.value,
  jar = (packageBin in Universal).value,
  s3Bucket = s3Bucket.value,
  lambdaName = lambdaName.value,
  handlerName = handlerName.value,
  lambdaHandlers = lambdaHandlers.value,
  roleArn = roleArn.value,
  timeout = awsLambdaTimeout.value,
  memory = awsLambdaMemory.value
)
```

**Comment by SummerStorm** [comment]
I second this. The fat jars created by sbt-assembly are unnecessarily large, and on my slow internet connection each jar upload takes minutes. It would be great if sbt-proguard could be supported to trim down the final jar size.
