### ISSUE TITLE
Lambda creation optional

### ISSUE THREAD

**Issue by lees-oz** [saksdirect/sbt-aws-lambda#53]
When managing infrastructure with tools such as Terraform, it would be handy to have the lambda creation optional. So it is possible to simply deploy jar to a specified lambda with minimum configuration (only lambda name required).

**Comment by gheine** [comment]
Using this sbt plugin for lambda creation and configuration updates is optional, you don't need to run `sbt configureLambda` at all. Just run `sbt deployLambda` which will package and deploy the current project to an existing AWS Lambda and not create or update the lambda config.
